import type { Catalog } from './types.js';

const ingredients = {
  burger: ['Mayonesa', 'Mostaza', 'Catsup', 'Lechuga', 'Tomate', 'Cebolla'],
  dog: ['Mayonesa', 'Mostaza', 'Catsup', 'Lechuga', 'Tomate', 'Cebolla'],
};

export const seedCatalog: Catalog = {
  version: '2026-09-15.1',
  categories: [
    {
      id: 'burgers',
      slug: 'hamburguesas',
      name: 'Hamburguesas',
      description: 'Carne al fuego y combinaciones de la casa.',
      order: 1,
      active: true,
    },
    {
      id: 'dogs',
      slug: 'hot-dogs',
      name: 'Hot dogs',
      description: 'Clásicos y especiales con sello B&J.',
      order: 2,
      active: true,
    },
    {
      id: 'sides',
      slug: 'complementos',
      name: 'Complementos',
      description: 'Para completar el plan.',
      order: 3,
      active: true,
    },
    {
      id: 'drinks',
      slug: 'bebidas',
      name: 'Bebidas',
      description: 'Presentación de 600 ml.',
      order: 4,
      active: true,
    },
  ],
  products: [
    {
      id: 'bj-smash',
      slug: 'bj-smash',
      categoryId: 'burgers',
      name: 'B&J Smash',
      description:
        'Doble carne smash, queso americano, tocino, cebolla caramelizada y aderezo especial B&J Smash.',
      priceCents: 10900,
      ingredients: [
        ...ingredients.burger,
        'Doble carne smash',
        'Queso americano',
        'Tocino',
        'Cebolla caramelizada',
        'Aderezo B&J',
      ],
      removableIngredients: [...ingredients.burger],
      comboEligible: true,
      featured: true,
      available: true,
      order: 1,
    },
    {
      id: 'clasica',
      slug: 'clasica',
      categoryId: 'burgers',
      name: 'Clásica',
      description: 'Carne Angus con queso americano y jamón.',
      priceCents: 6900,
      ingredients: [...ingredients.burger, 'Carne Angus', 'Queso americano', 'Jamón'],
      removableIngredients: [...ingredients.burger],
      comboEligible: true,
      featured: true,
      available: true,
      order: 2,
    },
    {
      id: 'hawaiana',
      slug: 'hawaiana',
      categoryId: 'burgers',
      name: 'Hawaiana',
      description: 'Carne Angus con queso americano, piña asada, queso asadero y jamón.',
      priceCents: 8900,
      ingredients: [...ingredients.burger, 'Piña asada', 'Queso asadero', 'Jamón'],
      removableIngredients: [...ingredients.burger],
      comboEligible: true,
      featured: false,
      available: true,
      order: 3,
    },
    {
      id: 'salchiburger',
      slug: 'salchiburger',
      categoryId: 'burgers',
      name: 'Salchiburger',
      description: 'Carne Angus con queso americano, salchichón y queso asadero.',
      priceCents: 8900,
      ingredients: [...ingredients.burger, 'Salchichón', 'Queso asadero'],
      removableIngredients: [...ingredients.burger],
      comboEligible: true,
      featured: false,
      available: true,
      order: 4,
    },
    {
      id: 'bbq',
      slug: 'bbq',
      categoryId: 'burgers',
      name: 'BBQ',
      description: 'Carne Angus, queso americano, aros de cebolla, tocino y salsa BBQ especial.',
      priceCents: 9900,
      ingredients: [...ingredients.burger, 'Aros de cebolla', 'Tocino', 'Salsa BBQ'],
      removableIngredients: [...ingredients.burger],
      comboEligible: true,
      featured: true,
      available: true,
      order: 5,
    },
    {
      id: 'monstruosa',
      slug: 'monstruosa',
      categoryId: 'burgers',
      name: 'Monstruosa',
      description:
        'Doble carne Angus, doble queso americano, salchichón, queso asadero, aros y doble tocino.',
      priceCents: 18900,
      ingredients: [
        ...ingredients.burger,
        'Doble carne Angus',
        'Doble queso',
        'Salchichón',
        'Aros de cebolla',
        'Doble tocino',
      ],
      removableIngredients: [...ingredients.burger],
      comboEligible: true,
      featured: true,
      available: true,
      order: 6,
    },
    {
      id: 'dog-clasico',
      slug: 'dog-clasico',
      categoryId: 'dogs',
      name: 'Dog Clásico',
      description: 'Salchicha premium con aderezos y vegetales.',
      priceCents: 5900,
      ingredients: [...ingredients.dog, 'Salchicha premium'],
      removableIngredients: [...ingredients.dog],
      comboEligible: true,
      featured: false,
      available: true,
      order: 1,
    },
    {
      id: 'bacon-dog',
      slug: 'bacon-dog',
      categoryId: 'dogs',
      name: 'Bacon Dog',
      description: 'Hot dog clásico con tocino.',
      priceCents: 6900,
      ingredients: [...ingredients.dog, 'Salchicha premium', 'Tocino'],
      removableIngredients: [...ingredients.dog],
      comboEligible: true,
      featured: false,
      available: true,
      order: 2,
    },
    {
      id: 'salchi-dog',
      slug: 'salchi-dog',
      categoryId: 'dogs',
      name: 'Salchi Dog',
      description: 'Salchichón, queso asadero, aderezos y vegetales.',
      priceCents: 6900,
      ingredients: [...ingredients.dog, 'Salchichón', 'Queso asadero'],
      removableIngredients: [...ingredients.dog],
      comboEligible: true,
      featured: false,
      available: true,
      order: 3,
    },
    {
      id: 'crispy-dog',
      slug: 'crispy-dog',
      categoryId: 'dogs',
      name: 'Crispy Dog',
      description: 'Salchicha premium, tocino, aros de cebolla y salsa BBQ de la casa.',
      priceCents: 8900,
      ingredients: [...ingredients.dog, 'Tocino', 'Aros de cebolla', 'Salsa BBQ'],
      removableIngredients: [...ingredients.dog],
      comboEligible: true,
      featured: true,
      available: true,
      order: 4,
    },
    {
      id: 'bj-dog',
      slug: 'bj-dog',
      categoryId: 'dogs',
      name: 'B&J Dog',
      description: 'Salchicha premium, tocino, queso asadero, cebolla caramelizada y salsa BBQ.',
      priceCents: 8900,
      ingredients: [
        ...ingredients.dog,
        'Tocino',
        'Queso asadero',
        'Cebolla caramelizada',
        'Salsa BBQ',
      ],
      removableIngredients: [...ingredients.dog],
      comboEligible: true,
      featured: true,
      available: true,
      order: 5,
    },
    {
      id: 'mix-dog',
      slug: 'mix-dog',
      categoryId: 'dogs',
      name: 'Mix Dog',
      description:
        'Media salchicha, medio salchichón, queso asadero, tocino, aderezos y vegetales.',
      priceCents: 8900,
      ingredients: [...ingredients.dog, 'Salchichón', 'Queso asadero', 'Tocino'],
      removableIngredients: [...ingredients.dog],
      comboEligible: true,
      featured: false,
      available: true,
      order: 6,
    },
    {
      id: 'papas-250',
      slug: 'papas-250',
      categoryId: 'sides',
      name: 'Orden de papas',
      description: 'Papas crujientes, porción de 250 g.',
      priceCents: 4900,
      ingredients: [],
      removableIngredients: [],
      comboEligible: false,
      featured: true,
      available: true,
      order: 1,
    },
    {
      id: 'aros-200',
      slug: 'aros-200',
      categoryId: 'sides',
      name: 'Aros de cebolla',
      description: 'Aros de cebolla crujientes, porción de 200 g.',
      priceCents: 5900,
      ingredients: [],
      removableIngredients: [],
      comboEligible: false,
      featured: false,
      available: true,
      order: 2,
    },
    {
      id: 'jalapeno-cremoso',
      slug: 'jalapeno-cremoso',
      categoryId: 'sides',
      name: 'Jalapeño Cremoso',
      description: 'Jalapeño relleno de queso crema.',
      priceCents: 2100,
      ingredients: [],
      removableIngredients: [],
      comboEligible: false,
      featured: false,
      available: true,
      order: 3,
    },
    ...['Coca-Cola|3600', 'Coca-Cola Zero|3100', 'Delaware|3100', 'Escuis|3100', 'Fanta|3100'].map(
      (entry, index) => {
        const [name = '', price = '0'] = entry.split('|');
        const id = name.toLowerCase().replaceAll(' ', '-');
        return {
          id,
          slug: id,
          categoryId: 'drinks',
          name,
          description: 'Refresco de 600 ml.',
          priceCents: Number(price),
          ingredients: [],
          removableIngredients: [],
          comboEligible: false,
          featured: false,
          available: true,
          order: index + 1,
        };
      },
    ),
  ],
  modifiers: [
    { id: 'extra-papas-150', name: 'Papas 150 g', priceCents: 1600, available: true },
    { id: 'extra-tocino', name: 'Tocino', priceCents: 1600, available: true },
    { id: 'extra-queso', name: 'Queso asadero', priceCents: 1600, available: true },
    { id: 'extra-pina', name: 'Piña asada', priceCents: 1600, available: true },
    { id: 'extra-salchichon', name: 'Salchichón', priceCents: 2100, available: true },
    { id: 'extra-carne', name: 'Carne extra', priceCents: 2600, available: true },
  ],
  promotions: [
    {
      id: 'jueves-clasico',
      name: 'Jueves Clásico',
      shortDescription: 'Dos hamburguesas desde $120; cambios pagando diferencia.',
      daysOfWeek: [4],
      startsAt: null,
      endsAt: null,
      priority: 10,
      active: true,
      rule: {
        kind: 'bundle_fixed',
        eligibleCategory: 'burgers',
        eligibleProductIds: [],
        baseProductId: 'clasica',
        requiredQuantity: 2,
        fixedPriceCents: 12000,
        allowPaidSubstitution: true,
        freeQuantity: 0,
      },
    },
    {
      id: 'viernes-papas',
      name: 'Viernes de papas gratis',
      shortDescription: 'Compra dos hamburguesas y recibe dos porciones de papas de 100 g.',
      daysOfWeek: [5],
      startsAt: null,
      endsAt: null,
      priority: 10,
      active: true,
      rule: {
        kind: 'free_item',
        eligibleCategory: 'burgers',
        eligibleProductIds: [],
        requiredQuantity: 2,
        freeItemLabel: 'Porción de papas 100 g',
        freeQuantity: 2,
        allowPaidSubstitution: false,
      },
    },
    {
      id: 'sabado-salchiburger',
      name: 'Sábado de Salchiburger',
      shortDescription: 'Salchiburger a precio especial de $79.',
      daysOfWeek: [6],
      startsAt: null,
      endsAt: null,
      priority: 10,
      active: true,
      rule: {
        kind: 'price_override',
        eligibleProductIds: ['salchiburger'],
        requiredQuantity: 1,
        unitPriceCents: 7900,
        allowPaidSubstitution: false,
      },
    },
    {
      id: 'domingo-para-dos',
      name: 'Domingo para dos',
      shortDescription: 'Dos hamburguesas y dos porciones de papas de 100 g desde $169.',
      daysOfWeek: [0],
      startsAt: null,
      endsAt: null,
      priority: 10,
      active: true,
      rule: {
        kind: 'bundle_fixed',
        eligibleCategory: 'burgers',
        eligibleProductIds: [],
        baseProductId: 'hawaiana',
        requiredQuantity: 2,
        fixedPriceCents: 16900,
        freeItemLabel: 'Porción de papas 100 g',
        freeQuantity: 2,
        allowPaidSubstitution: true,
      },
    },
  ],
  business: {
    name: 'B&J Burgers',
    slogan: 'Más que burgers, es un plan',
    whatsappNumber: '528333514381',
    phoneDisplay: '833 351 4381',
    timezone: 'America/Mexico_City',
    freeDeliveryArea: 'Canarios',
    deliveryNotice:
      'Entrega gratis en Canarios. En otras zonas confirmamos cobertura y costo por WhatsApp.',
    temporarilyClosed: false,
    closureMessage: 'Hoy no tendremos servicio',
    updatedAt: '2026-09-15T00:00:00.000Z',
    schedule: [4, 5, 6, 0].map((dayOfWeek) => ({ dayOfWeek, opens: '18:00', closes: '23:55' })),
  },
};
